version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: rlt.nginx
    ports:
      - 8080:80
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: docker/php-fpm
    container_name: rlt.php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
  postgresql:
    image: 'bitnami/postgresql:latest'
    restart: always
    labels:
      kompose.service.type: nodeport
    ports:
      - '5434:5432'
    volumes:
      - 'postgresql_data:/bitnami'
    environment:
    - POSTGRES_USER=rlt
    - POSTGRES_PASSWORD=rlt
    - POSTGRES_DB=rlt_api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: rlt.elasticsearch
    restart: always
    ports:
    - 9200:9200
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    volumes:
    - elasticdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: rlt.kibana
    restart: always
    ports:
    - 5601:5601
    volumes:
    - kibanadata:/usr/share/elasticsearch/data

volumes:
  postgresql_data:
    driver: local
  elasticdata:
    driver: local
  kibanadata:
    driver: local
