# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # by FOS REST we include any controller to service
    RltBundle\Controller\:
        resource: '../../src/RltBundle/Controller/*'


    RltBundle\Service\ParseListInterface: '@RltBundle\Service\BuildingService'

    # Buildings New
    RltBundle\Service\BuildingService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\BuildingParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\BuildingValidatorManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\BuildingNewParserCommand:
      arguments: ['@RltBundle\Service\BuildingService', '@RltBundle\Manager\BuildingParserManager', '@RltBundle\Manager\BuildingValidatorManager']
      tags:
      - { name: console.command }

    # Buildings Update
    RltBundle\Command\BuildingUpdateParserCommand:
      arguments: ['@RltBundle\Service\BuildingService', '@RltBundle\Manager\BuildingParserManager', '@RltBundle\Manager\BuildingValidatorManager']
      tags:
      - { name: console.command }

    # Developers
    RltBundle\Service\DeveloperService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\DeveloperParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\DeveloperValidatorManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\DeveloperNewParserCommand:
      arguments: ['@RltBundle\Service\DeveloperService', '@RltBundle\Manager\DeveloperParserManager', '@RltBundle\Manager\DeveloperValidatorManager']
      tags:
      - { name: console.command }

    # banks
    RltBundle\Service\BankService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\BankParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\BankValidatorManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\BankNewParserCommand:
      arguments: ['@RltBundle\Service\BankService', '@RltBundle\Manager\BankParserManager', '@RltBundle\Manager\BankValidatorManager']
      tags:
      - { name: console.command }

    # News
    RltBundle\Service\NewsService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\NewsParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\NewsValidatorManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\NewsNewParserCommand:
      arguments: ['@RltBundle\Service\NewsService', '@RltBundle\Manager\NewsParserManager', '@RltBundle\Manager\NewsValidatorManager']
      tags:
      - { name: console.command }

    # News
    RltBundle\Service\MetroParserManager:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Command\MetroParserCommand:
      arguments: ['@RltBundle\Service\MetroParserManager']
      tags:
        - { name: console.command }

    # JWTCreatedListener
    RltBundle\Listeners\JWTCreatedListener:
      tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    RltBundle\Tests\DataFixtures\:
      resource: '../../src/RltBundle/Tests/DataFixtures/*'
      tags: ['doctrine.fixture.orm']