# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # by FOS REST we include any controller to service
    RltBundle\Controller\:
        resource: '../../src/RltBundle/Controller/*'


    RltBundle\Service\ParseListInterface: '@RltBundle\Service\BuildingService'

    # Buildings New
    RltBundle\Service\BuildingService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\ParserManager\BuildingParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\FillerManager\BuildingFillerManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\BuildingParserCommand:
      arguments: ['@RltBundle\Service\BuildingService','@RltBundle\Manager\ParserManager\BuildingParserManager','@RltBundle\Manager\FillerManager\BuildingFillerManager']
      tags:
      - { name: console.command }

    # Developers
    RltBundle\Service\DeveloperService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\ParserManager\DeveloperParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\FillerManager\DeveloperFillerManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\DeveloperParserCommand:
      arguments: ['@RltBundle\Service\DeveloperService','@RltBundle\Manager\ParserManager\DeveloperParserManager','@RltBundle\Manager\FillerManager\DeveloperFillerManager']
      tags:
      - { name: console.command }

    # banks
    RltBundle\Service\BankService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\ParserManager\BankParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\FillerManager\BankFillerManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\BankParserCommand:
      arguments: ['@RltBundle\Service\BankService','@RltBundle\Manager\ParserManager\BankParserManager','@RltBundle\Manager\FillerManager\BankFillerManager']
      tags:
      - { name: console.command }

    # News
    RltBundle\Service\NewsService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Manager\ParserManager\NewsParserManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Manager\FillerManager\NewsFillerManager:
      arguments: ['@doctrine.orm.default_entity_manager', '@logger']
      public: true

    RltBundle\Command\NewsParserCommand:
      arguments: ['@RltBundle\Service\NewsService','@RltBundle\Manager\ParserManager\NewsParserManager','@RltBundle\Manager\FillerManager\NewsFillerManager']
      tags:
      - { name: console.command }

    # News
    RltBundle\Service\MetroService:
      arguments: ['%parser_host%']
      public: true

    RltBundle\Command\MetroParserCommand:
      arguments: ['@RltBundle\Service\MetroService']
      tags:
        - { name: console.command }

    # JWTCreatedListener
    RltBundle\Listeners\JWTCreatedListener:
      tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    RltBundle\Tests\DataFixtures\:
      resource: '../../src/RltBundle/Tests/DataFixtures/*'
      tags: ['doctrine.fixture.orm']