easy_admin:
  entities:
    Bank:
      class: RltBundle\Entity\Bank
      label: 'Banks'
      list:
        actions:
          - { name: 'new', label: 'Create bank', icon: 'plus' }
        title: "Banks list"
        fields:
          - { property: 'name', label: 'Name' }
          - { property: 'phone', label: 'Phone'}
          - { property: 'site', label: 'Site'}
          - { property: 'creationYear', label: 'Founded at'}
      form:
        fields:
          - { property: 'externalId', type: 'text', label: 'External ID', type_options: { disabled: true }}
          - { property: 'name', type: 'text', label: 'Name' }
          - { property: 'address', type: 'text', label: 'Address'}
          - { property: 'phone', type: 'text', label: 'Phone'}
          - { property: 'site', type: 'text', label: 'Site'}
          - { property: 'creationYear', type: 'text', label: 'Founded at'}
          - { property: 'logo', type: 'RltBundle\Form\FilesType', help: 'Max filesize - 5Mb', type_options: { label: 'Logo file', by_reference: false, data_class: 'RltBundle\Entity\Files\BankFiles', value_type: 'Vich\UploaderBundle\Form\Type\VichImageType'}}
          - { property: 'description', type: 'textarea', type_options: { label: 'Description', by_reference: false }}
      new:
        title: 'Create bank'
      edit:
        title: 'Edit bank %%entity_id%%'