easy_admin:
  entities:
    Building:
      class: RltBundle\Entity\Building
      label: 'Buildings'
      list:
        actions:
          - { name: 'new', label: 'Create building', icon: 'plus' }
        title: "Buildings list"
        fields:
          - { property: 'name', label: 'Name' }
      form:
        fields:
          - { property: 'name', type: 'text', type_options: { label: 'Name' } }
      new:
        title: 'Create building'
      edit:
        title: 'Edit building %%entity_id%%'