easy_admin:
  design:
    brand_color: '#205081'
    form_theme:
      - '@EasyAdmin/form/bootstrap_3_horizontal_layout.html.twig'
    menu:
      - label: 'Пользователи и роли'
        children:
          - { label: 'Пользователи', entity: 'User', icon: 'calendar', default: true }
          - { label: 'Роли', entity: 'Group', icon: 'calendar' }
