easy_admin:
  design:
    brand_color: '#205081'
    form_theme:
      - '@EasyAdmin/form/bootstrap_3_horizontal_layout.html.twig'
    menu:
      - label: 'Users and roles'
        children:
          - { label: 'Users', entity: 'User', icon: 'calendar', default: true }
          - { label: 'Roles', entity: 'Group', icon: 'calendar' }
          - { label: 'Banks', entity: 'Bank', icon: 'calendar' }
          - { label: 'Developers', entity: 'Developer', icon: 'calendar' }
          - { label: 'News', entity: 'News', icon: 'calendar' }
          - { label: 'Buildings', entity: 'Building', icon: 'calendar' }
