easy_admin:
  brand_color: '#205081'
  form_theme:
    - '@EasyAdmin/form/bootstrap_3_horizontal_layout.html.twig'
  entities:
    User:
      class: RltBundle\Entity\User
      form:
        fields:
          - username
          - email
          - lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'password', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }