easy_admin:
  entities:
    Group:
      class: RltBundle\Entity\Group
      label: 'Roles'
      list:
        actions:
          - { name: 'new', label: 'Create role', icon: 'plus' }
        title: "Roles list"
        fields:
          - { property: 'name', label: 'Name' }
      form:
        fields:
          - { property: 'name', type: 'text', type_options: { label: 'Name' } }
      new:
        title: 'Create role'
      edit:
        title: 'Edit role %%entity_id%%'