easy_admin:
  entities:
    User:
      class: RltBundle\Entity\User
      label: 'Users'
      list:
        actions:
          - { name: 'new', label: 'Create user', icon: 'plus' }
        title: "Users list"
        fields:
          - username
          - email
          - enabled
          - { property: 'last_login', template: 'admin/fields/datetime_field.html.twig' }
      form:
        fields:
          - { property: 'username', type: 'text', type_options: { label: 'Login' } }
          - { property: 'email', type: 'text', type_options: { label: 'Email' } }
          - { property: 'enabled', type: 'checkbox', type_options: { label: 'Activity' } }
      new:
        title: 'Create user'
      edit:
        title: 'Edit user %%entity_id%%'