FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            exclude: false
            groups: ['users', 'getBuildings']
        email:
            exclude: false
            groups: ['users']
        id:
            exclude: false
            groups: ['users', 'getBuildings']