FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            exclude: false
            groups: ['getUser']
        email:
            exclude: false
            groups: ['getUser']
        id:
            exclude: false
            groups: ['getUser']
        groups:
            exclude: false
            groups: ['getUser']