FOS\UserBundle\Model\Group:
    exclusion_policy: ALL
    properties:
        id:
            exclude: false
            groups: ['getGroup']
        name:
            exclude: false
            groups: ['getGroup']
        roles:
            exclude: false
            groups: ['getGroup', 'getUser']

