<?php

namespace RltBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistrictRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends EntityRepository
{
    public const TABLE = 'rlt_districts';
    public const NAME = 'RltBundle:District';

    /**
     * Entity full signature (with bundle name, like "RltBundle:User").
     *
     * @return string
     */
    public function getEntitySignature(): string
    {
        return self::NAME;
    }

    /**
     * Alias for table that will be used in DQL.
     *
     * @return string
     */
    public function getAlias(): string
    {
        return 'dt';
    }
}
