<?php

namespace RltBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getAlias(): string
    {
        return 'u';
    }

    /**
     * {@inheritdoc}
     */
    public function getEntitySignature(): string
    {
        return 'RltBundle:User';
    }
}
